sudo: required
language: csharp
mono: none
dotnet: 2.1.300
if: tag IS blank
services:
  - docker
before_install:
  - git fetch --unshallow
  - printf "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}\n" >> ~/.npmrc
script:
  - ./build.sh ci